### ISSUE TITLE
Shuffle errors out

### ISSUE THREAD

**Issue by 02Miki** [sarhatabaot/Composer#11]
It throws this error:

[08:46:25] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'music shuffle' for source EntityPlayerMP['02Miki'/5, l='Spoolyville', x=687.12, y=5.00, z=-658.34]: null
java.lang.UnsupportedOperationException: null
        at java.util.Collections$UnmodifiableList.set(Collections.java:1311) ~[?:1.8.0_212]
        at java.util.Collections.swap(Collections.java:497) ~[?:1.8.0_212]
        at java.util.Collections.shuffle(Collections.java:458) ~[?:1.8.0_212]
        at java.util.Collections.shuffle(Collections.java:425) ~[?:1.8.0_212]
        at se.walkercrou.composer.nbs.MusicPlayer.shuffle(MusicPlayer.java:168) ~[MusicPlayer.class:?]
        at se.walkercrou.composer.cmd.ComposerCommands.shuffleTracks(ComposerCommands.java:157) ~[ComposerCommands.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.6-RC3616]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.6-RC3616]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3616]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3616]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by sarhatabaot** [comment]
Does this happen while using the tracks folder?

**Comment by sarhatabaot** [comment]
Fixed in 716dbfd1337cf356e01ad33df5d342ca7b5eb638
